### ISSUE TITLE
Allow less blur

### ISSUE THREAD

**Issue by Fxsch** [officialLennox/rainbowify#11]
Even when `Blur Amount` is set to `1`, the blur is still quite strong. I would prefer it if the blur could be set lower than that. In the [Blur mod](https://modrinth.com/mod/blur-fabric), for example, the blur radius can be set all the way down to 1 or even 0, while in this mod a Blur Amount of 1 is clearly a lot higher than that.

**Comment by lennoxlotl** [comment]
sure

**Comment by lennoxlotl** [comment]
There will be a new setting in the version ill release in a bit where you can adjust the blur iterations giving you the ability to fully customize the blur

**Comment by Fxsch** [comment]
That's great, thanks

**Comment by lennoxlotl** [comment]
The update has been pushed.

https://modrinth.com/mod/rainbowify/version/2.0.0-alpha.3
https://github.com/officialLennox/rainbowify/releases/tag/2.0.0-alpha.3
