### ISSUE TITLE
Minecraft crashes if you alt-tab while in the inventory

### ISSUE THREAD

**Issue by SimplyTolex** [officialLennox/rainbowify#14]
To crash, you just in to enable `Rainbowify` and `blur` (any amount will do) in the config
Then make a blur show up by opening pause menu, inventory, chest, etc.
Then alt-tab and, after any amount of time, open the game again
The game will crash
![26-12 36 18--javaw_FX0el](https://user-images.githubusercontent.com/50412868/186830592-c320172e-b91f-43a7-82ce-b90d9f8a5c00.png)
here is log
[latest.log](https://github.com/officialLennox/rainbowify/files/9430141/latest.log)
and here are *4* crash logs (I was experimenting with what makes the game to crash)
[crash-2022-08-26_12.32.21-client.txt](https://github.com/officialLennox/rainbowify/files/9430144/crash-2022-08-26_12.32.21-client.txt)
[crash-2022-08-26_12.36.09-client.txt](https://github.com/officialLennox/rainbowify/files/9430145/crash-2022-08-26_12.36.09-client.txt)
[crash-2022-08-26_12.38.22-client.txt](https://github.com/officialLennox/rainbowify/files/9430147/crash-2022-08-26_12.38.22-client.txt)
[crash-2022-08-26_12.41.30-client.txt](https://github.com/officialLennox/rainbowify/files/9430149/crash-2022-08-26_12.41.30-client.txt)

forgot to mention, the version is `1.18.2` and mod version `1.2.1`

**Comment by lennoxlotl** [comment]
Hey, thanks for the report, I will try to fix this as soon as I am back home.

**Comment by lennoxlotl** [comment]
This issue won't be fixed as I don't provide support for outdated Minecraft Versions (at the moment, might change later on)
