### ISSUE TITLE
setting screen not work well with Bedrockify and mark it as support 1.19.1(2.0.0 Alpha3)

### ISSUE THREAD

**Issue by x-yingcan-x** [officialLennox/rainbowify#15]
![搜狗截图22年08月27日1404_1](https://user-images.githubusercontent.com/99530733/187017629-ac89b434-48cc-43e4-888d-cf8b3a6f4e7f.png)
button still works,but is obscured.(delete Bedrockify and it works fine)
it work on 1.19.1 with many other mods.

**Comment by lennoxlotl** [comment]
fixed in next version
