### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by cerealconjugo** [officialLennox/rainbowify#2]
}}
[crash-2021-07-26_12.47.13-client.txt](https://github.com/officialLennox/rainbowify/files/6880810/crash-2021-07-26_12.47.13-client.txt)

**Comment by lennoxlotl** [comment]
Can you please supply the full log as this is related to the shader not loading

**Comment by lennoxlotl** [comment]
Also please join our discord, it can be found in the readme. I can give you proper support there

**Comment by cerealconjugo** [comment]
of curse!

**Comment by lennoxlotl** [comment]
This issue has been resolved and will be fixed in the new update.
