### ISSUE TITLE
Incompatibility with 'Slight' Gui Modifications

### ISSUE THREAD

**Issue by csutora** [officialLennox/rainbowify#4]
Rainbowify and ['Slight' Gui Modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications) seem to be incompatible.

The game crashes before the main window would have a chance to open.
I'm running 1.17.1 from multimc, everything is latest. 
Removing either mod fixes the issue. I have sodium and indium installed.

Here's the [full crash report.](https://paste.ee/p/Jn9g5)

I've reported this to both mods' issue tracker, and I'll update both issues with info from the other.

**Comment by lennoxlotl** [comment]
I will fix this issue as soon as I have time available to do it.

**Comment by lennoxlotl** [comment]
This issue will be fixed in the next release.
